# Build Stage - ADMIN
FROM node:20-alpine AS build

WORKDIR /app

COPY package.json yarn.lock* package-lock.json* ./

# Install dependencies
RUN npm install --legacy-peer-deps
RUN npm install ajv@^8.0.0 --legacy-peer-deps

COPY . .

# Build como ADMIN
# REACT_APP_BACKEND_URL deve ser passado como build-arg
ARG REACT_APP_BACKEND_URL
ENV REACT_APP_MODE=admin
ENV REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL:-}
RUN npm run build

# Production Stage
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
